import re
from pypdf import PdfReader


def extract_paragraphs(uploaded_file) -> list[str]:
    reader = PdfReader(uploaded_file)
    full_text = ""
    for page in reader.pages:
        text = page.extract_text() or ""
        # Clean up page numbers / headers like "--- PAGE 1 ---"
        text = re.sub(r'---\s*PAGE\s*\d+\s*---', '', text, flags=re.IGNORECASE)
        full_text += text + "\n\n"

    # Remove generic footer metadata
    full_text = re.sub(r'Generated by.*?$', '', full_text, flags=re.IGNORECASE | re.MULTILINE)

    # 1. Smart boundary detection for numbered bugs (e.g., Bug 1, Bug #1, Bug 1:, Bug # 12)
    # Using a positive lookahead to split the text right before "Bug"
    chunks = re.split(r'(?i)(?=Bug\s*#?\s*\d+\b)', full_text)
    
    paras = []
    for chunk in chunks:
        # Check if this chunk is an actual Bug block (ignores intro tables/metadata)
        if re.match(r'(?i)\s*Bug\s*#?\s*\d+\b', chunk):
            
            # Replace single newlines with spaces to fix broken PDF sentences
            cleaned = re.sub(r'(?<!\n)\n(?!\n)', ' ', chunk)
            cleaned = re.sub(r'\s+', ' ', cleaned).strip()
            
            # General Heuristic: If the text contains quotes, the longest quote 
            # is almost always the actual bug description (ignores metadata/solutions).
            quotes = re.findall(r'"([^"]*)"', cleaned)
            if quotes:
                longest_quote = max(quotes, key=len)
                if len(longest_quote) > 20:
                    paras.append(longest_quote.strip())
                    continue
            
            # Fallback: keep the whole cleaned chunk if no quotes are found
            if len(cleaned) > 20:
                paras.append(cleaned)

    if paras:
        return paras

    # --- 2. Fallback for general PDFs (no "Bug #X" markers) ---
    clean_text = re.sub(r'(?<!\n)\n(?!\n)', ' ', full_text)
    blocks = re.split(r'\n{2,}', clean_text)
    for b in blocks:
        cleaned = re.sub(r'\s+', ' ', b).strip()
        # Ignore purely numeric/symbol tables and very short metadata
        if len(cleaned) > 20 and not re.match(r'^[\d\s,.\-%]+$', cleaned):
            paras.append(cleaned)

    # 3. Last resort: sentence splitting
    if len(paras) <= 1 and len(full_text) > 50:
        by_sentence = re.split(r'(?<=[.!?])\s{1,}', clean_text)
        paras = [p.strip() for p in by_sentence if len(p.strip()) > 15]

    return paras if paras else [full_text.strip()]


def split_text_input(raw: str) -> list[str]:
    # Use the same robust regex for manual text inputs
    chunks = re.split(r'(?i)(?=Bug\s*#?\s*\d+\b)', raw)
    bugs = []
    for chunk in chunks:
        if re.match(r'(?i)\s*Bug\s*#?\s*\d+\b', chunk):
            cleaned = re.sub(r'\s+', ' ', chunk).strip()
            quotes = re.findall(r'"([^"]*)"', cleaned)
            if quotes:
                longest_quote = max(quotes, key=len)
                if len(longest_quote) > 20:
                    bugs.append(longest_quote.strip())
                    continue
            if len(cleaned) > 10:
                bugs.append(cleaned)
    
    if bugs:
        return bugs

    # Fallback to double newline split
    by_newline = re.split(r'\n+', raw)
    if len(by_newline) > 1:
        bugs = [p.strip() for p in by_newline if len(p.strip()) > 10]
        if bugs: return bugs

    # Final fallback to sentence split
    by_sentence = re.split(r'(?<=[.!?])\s{2,}', raw)
    bugs = [p.strip() for p in by_sentence if len(p.strip()) > 10]
    return bugs if bugs else [raw]


def clean_bug_text(text: str, max_chars: int = 500) -> str:
    text = re.sub(r'\s+', ' ', text).strip()
    return text[:max_chars] + ("..." if len(text) > max_chars else "")